//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.Comments = new HashSet<Comment>();
            this.TextContents = new HashSet<TextContent>();
            this.Votes = new HashSet<Vote>();
        }
    
        public string ArticleID { get; set; }
        public string SubjectID { get; set; }
        public System.DateTime AddTime { get; set; }
        public string UserID { get; set; }
        public string Tittle { get; set; }
        public string ContentID { get; set; }
        public long ContentType { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TextContent> TextContents { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
