//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB.Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public Vote()
        {
            this.VoteItems = new HashSet<VoteItem>();
        }
    
        public string VoteID { get; set; }
        public int IsMultiple { get; set; }
        public string ArticleID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<VoteItem> VoteItems { get; set; }
    }
}
